- CHANGELOG.md
- README.md
- package.json
- src/cli/index.ts
- src/cli/init.ts
- src/cli/run.ts
- src/configs/ci/github-actions.ts
- src/configs/ci/index.ts
- src/configs/index.ts
- src/lib/files.spec.ts
- src/lib/files.ts
- src/lib/handlebars.spec.ts
- src/lib/handlebars.ts
- src/presets/index.ts
- src/types/shared.ts
- yarn.lock
All the linting and test presets from Foundry don't help if they're not run regularly against the code. Ideally, they run on every push in CI.
- add a new CI preset that bootstraps a GitHub Actions workflow with the scripts from the presets that are being configured
> feat(ci): add CI preset

- src/configs/prettier/__snapshots__/config.spec.ts.snap
- src/configs/prettier/config.ts
- src/lib/files.ts
Explicitly setting the `parser` option prevented prettier from parsing and formatting other file
formats based on their file extension.
- remove hard-coded `parser` option from prettier config
> fix(prettier): infer parser from file extension

- src/configs/plop/templates/js/class-component.hbs
- src/configs/plop/templates/js/functional-component.hbs
- src/configs/plop/templates/js/styled-component.hbs
- src/configs/plop/templates/ts/class-component.hbs
- src/configs/plop/templates/ts/functional-component.hbs
- src/configs/plop/templates/ts/styled-component.hbs
In the component templates, as a description for prop types, `concise` was spelled `consice`.
Fix all occurrences of the typo in the templates.
> fix: correct typo in component template

- README.md
- src/cli/index.ts
I forgot to add the new CI preset to the CLI options and help menu.
- add CI preset and options to help menu
> docs(ci): add CI preset to help menu

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
- src/configs/eslint/index.ts
While scaffolding the new SumUp + Next.js + TypeScript starter, I found a few issues and opportunities for improvement of the TypeScript Eslint rules.
- Do not lint tooling config files. Eslint complains because they're usually not included in the `tsconfig.json`. They're usually generated by Foundry anyway.
- Add `.tsx` to the resolved extensions. No idea how I missed that one before 👀
- Turn off warning about function return type for JS files.
- Turn off `spaced-comment` rule in type declaration files since they break the `/// <reference types="next" />` syntax
- Apply rules for test files also to `'**/setupTests.*` and `**/test-utils.*`
> feat(eslint): improve TypeScript rules

- .github/workflows/ci.yaml
- src/configs/ci/github-actions.ts
The caching of the node modules in CI doesn't seem to work, because `yarn` caches modules differently.
- adapt caching setup from the [official docs](https://github.com/actions/cache/blob/master/examples.md#node---yarn)
> perf(ci): improve caching when using yarn

- src/lib/files.spec.ts
- src/lib/files.ts
- src/types/shared.ts
Fixes #97.
`foundry init` doesn't add custom commands to `package.json` when the package doesn't contain the `scripts` property.
- Initialize the `scripts` property if it doesn't exist yet
> fix(init): initialize package scripts

- src/configs/plop/templates/ts/component-spec.hbs
- src/configs/plop/templates/ts/service-spec.hbs
The `create:component` command can bootstrap test files. The test cases are empty at first and Jest complains about them. 
- mark incomplete tests as todo using `it.todo()`
> feat(templates): mark empty tests as todo

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
The [`explicit-function-return-type`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) rule is more annoying than helpful. In most cases, TypeScript is able to infer the type, so the explicit type is not necessary. TypeScript and Eslint should be helpful, not annoying and cumbersome.
- disable `explicit-function-return-type` rule
> feat(eslint): turn off explicit-function-return-type rule

- CONTRIBUTING.md
- README.md
- src/configs/semantic-release/__snapshots__/config.spec.ts.snap
- src/configs/semantic-release/config.spec.ts
- src/configs/semantic-release/config.ts
The origin of the "master" name for the default git branch is [likely rooted](https://boleary.dev/blog/2020-06-10-i-was-wrong-about-git-master.html) in master/slave terminology.
[Una Kravets](https://twitter.com/Una) summarized the arguments for switching to "main" in [a tweet](https://twitter.com/Una/status/1271181775130279936):
> 1. “Main” is shorter! Yay brevity!
> 2. It’s even easier to remember, tbh
> 3. If it makes any of my teammates feel an ounce more comfortable, let’s do it!
> 4. If it prevents even a single black person from feeling more isolated in the tech community, feels like a no brainer to me!
- Add "main" to the list of branches on which semantic-release should run. Note that "master" is still supported to make the transition easier. It will be removed in the next major. …
> feat(release): rename default git branch to "main"

- src/configs/plop/templates/js/component-spec.hbs
- src/configs/plop/templates/js/styled-component.hbs
- src/configs/plop/templates/ts/component-spec.hbs
- src/configs/plop/templates/ts/functional-component.hbs
- src/configs/plop/templates/ts/story.hbs
- src/configs/plop/templates/ts/styled-component.hbs
- Remove FunctionComponent type based on @fernandofleury's suggestion in https://github.com/sumup-oss/circuit-ui/pull/615#discussion_r442273911
- Remove default props since will drop support for them eventually and they can be replaced by [default function params](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)
- Update unit tests to avoid test/lint errors after the initial generation
> feat(plop): update default templates

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
Addresses #123.
Fix linting and formatting of JSON files in open source TypeScript projects.
Disables the ESLint notice plugin in JSON files via an override. The plugin
insisting the need for a copyright header in a JSON file and also causing issues
with the @typescript-eslint/parser configuration.
I'm not adding any tests for this as this is purely declarative and there are no
existing tests for ESLint rules.
> fix(lint): disable ESlint notice plugin for JSON

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
- src/configs/eslint/index.ts
Addresses #123.
Eslint fails on linting `.json` files when TypeScript is used.
- Include `.json` files in the Eslint parser config
- Ignore the `tsconfig.json` file for Eslint since it is excluded by TypeScript by default
You might still have to manually edit your `tsconfig.json` file to include `.json` files. Make sure you've set `compilerOptions.resolveJsonModule` to `true` and included `.json` files in the `include` option.
> fix(lint): include JSON files when linting TypeScript

- CONTRIBUTING.md
Getting local development to work was a bit less straight forward than I
thought.
Add a Development section to the contributing guidelines.
> docs(contrib): add development workflow

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
The upgrade of Eslint and its plugins (#121) wrongly enforced typings-related rules in JavaScript files.
- Disable TypeScript rules in JavaScript files
> fix(lint): disable TypeScript rules in JavaScript files

- src/configs/plop/templates/ts/component-spec.hbs
The [`create-sumup-react-app`](https://github.com/sumup/create-sumup-react-app) and [`create-sumup-next-app`](https://github.com/sumup/create-sumup-next-app) starters are being updated. The location of the `test-utils` file has changed, this should be reflected in Foundry.
- update the import in the spec template to point to the project root
- simplify the spec template: the `render` function covers all use cases
> feat(template): update spec file template

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
The test-specific ESLint rules should only apply to test files. This improves linting performance and prevents false positives.
- Move `plugin` and `extend` options into the `overrides`
> feat(lint): scope test-specific ESLint rules

- src/configs/plop/config.ts
Closes #264.
- add `targetDir` option to Plop which determines where Plop saves the generated files, defaults to `./src/components`
> feat(plop): add option for target dir

- .github/prepare-github-release
- .github/workflows/ci.yaml
GitHub Packages does not allow you to install both private and public packages within the same scope. That's why need to publish OSS packages to the `@sumup-oss` scope in GitHub Packages.
- publish Foundry to GitHub Packages under the name `@sumup-oss/foundry`
> chore: publish to GitHub Packages registry

- .eslintrc.js
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.spec.ts
- src/configs/eslint/config.ts
- src/configs/eslint/index.ts
Many of ESLint's TypeScript-specific rules are too strict or don't make sense when applied to JavaScript files. Plus, it can be confusing when adding TypeScript to a project, when lint issues are flagged in JavaScript files, that weren't flagged before.
- Scope the TypeScript plugins and rules to `.ts` and `.tsx` files. This enables the TypeScript rules to be included by default, making the `language` option for ESLint obsolete.
BREAKING CHANGE: ESLint's TypeScript rules are now automatically applied to `.ts` and `.tsx` files
only.
> feat(lint): apply TS rules automatically and to TS files only 

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- README.md
- package.json
- src/configs/ci/github-actions.ts
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
The order of ESLint overrides matters: lower overrides take precedence. 
Requiring Node v14+ isn't really necessary and only makes our life more difficult when upgrading.
- tweak ESLint rules
- lower minimum Node version to v12+
> feat(lint): tweak ESLint rules

- yarn.lock
ESLint had an accidental breaking change in a minor version which causes an error with the Airbnb preset and `eslint-plugin-import` (see https://github.com/airbnb/javascript/issues/2331). 
- Upgrade all dependencies to their latest minor, particularly `eslint-plugin-import` to `> 2.22.1`
> fix: upgrade dependencies to latest minor

- CODE_OF_CONDUCT.md
Same as https://github.com/sumup-oss/circuit-ui/pull/1381.
Copies the Contributor Covenant over, tweaked the contact method to point to the list of maintainers on the README
> Update Contributor Covenant to v2.1

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
Addresses https://github.com/sumup/ze-dashboard/pull/5395/files#r802550229.
ESLint complains about mocked methods being unbound in spec files.
- Disable the two "unbound method" rules in spec files
> feat: disable unbound method rule for spec files

- package.json
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
- yarn.lock
In the [RFC to drop support for legacy browsers](https://sumupteam.atlassian.net/wiki/spaces/DEV/pages/2786787641/RFC+Dropping+support+for+legacy+browsers#Ensuring-future-browser-compatibility) (internal link), I wrote:
> In the past, developers have accidentally and unknowingly broken compatibility with legacy browsers causing the application to crash and show a blank screen. Error tracking can help here, but at that point, it’s already too late. It would be better if we could catch compatibility issues before they’re even committed.
> 
> Enter [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) and [stylelint-no-unsupported-browser-features](https://www.npmjs.com/package/stylelint-no-unsupported-browser-features). These lint JavaScript and CSS respectively and warn …
> feat: add ESLint plugin for browser compatibility

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
The `react-hooks/exhaustive-deps` was treated as a warning so far and thus ignored by developers. This is a [bad](https://typeofnan.dev/you-probably-shouldnt-ignore-react-hooks-exhaustive-deps-warnings/) [idea](https://dev.to/wkrueger/never-ignore-the-exhaustive-deps-rule-2ap8).
- Enable all recommended React hook rules as errors
BREAKING CHANGE: Missing dependencies of React hooks are now treated as an ESLint error.
> feat(eslint): enable all recommended React hook rules

- README.md
- package.json
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
- src/types/shared.ts
- yarn.lock
[Next.js](https://nextjs.org/) has become SumUp's default framework for building React applications.
- Add `Next.js` as an option to the frameworks
- Warn when the `Next.js` and `React` framework options are used together as they might conflict.
> feat(eslint): add preset for Next.js

- README.md
- package.json
- src/cli/init.ts
- src/configs/eslint/config.spec.ts
- src/configs/eslint/config.ts
- src/lib/files.spec.ts
- src/lib/files.ts
- src/types/shared.ts
- yarn.lock
The list of supported frameworks keeps getting longer. It's easy for developers to miss newly added frameworks or forget to update the ESLint config when installing a new framework.
Instead, we can detect the used frameworks based on the installed project dependencies.
- Automatically detect frameworks based on the installed dependencies
> feat: automatically detect used frameworks

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
Configuring ESLint for isomorphic frameworks such as Next.js is tricky since different rules need to apply to code that runs in the browsers vs in Node.js. This PR turns off some rules for [API routes](https://nextjs.org/docs/api-routes/introduction) that don't apply in a Node.js context.
- Disable the `compat` plugin for API routes. Ideally, we'd keep it enabled and configure it for Node.js, however, I couldn't find a straightforward way to provide a separate `browserslist` config file for it.
- Disable the `no-console` rule for API routes. Logs can be inspected in Vercel or a log drain if one has been set up.
> feat(eslint): improve ESLint rules for API routes

- .changeset/early-impalas-rhyme.md
- CONTRIBUTING.md
- package.json
When switching to `changesets` for release automation (#752), I forgot that Foundry is released from _inside_ the `/dist` folder. This was done to keep the import paths for configs clean (e.g. `import createConfig from '@sumup/foundry/eslint';`).
The new `exports` field offers a better way to define [package entry points](https://nodejs.org/api/packages.html#package-entry-points).
- Replace `main` with `exports` in `package.json` (supported in Node 11+)
> Switch to package exports

- .changeset/neat-frogs-develop.md
- package.json
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
> Error while loading rule 'jest/unbound-method': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
> In order to use the rules powered by TypeScript type-checking, you must be using @typescript-eslint/parser & adjust your eslint config as outlined [here](https://typescript-eslint.io/linting/typed-linting).
- Enabled type checking for unit test files to provide required type information to the `jest/unbound-method` rule.
> Enable type information for jest/unbound-method

- package-lock.json
- package.json
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
Add [eslint plugin security](https://github.com/eslint-community/eslint-plugin-security) for node environment.
Added to eslint config the recommend config of the plugin when environment is node.
> Add eslint-plugin-security for Node environments

- .changeset/empty-eagles-rule.md
- package-lock.json
- package.json
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
- src/lib/options.spec.ts
- src/lib/options.ts
- src/types/shared.ts
Storybook [released](https://storybook.js.org/blog/how-to-use-storybook-with-eslint/) an official ESLint plugin 2 years ago.
- Enable Storybook's ESLint plugin with the recommended rules if `storybook` is installed
> Add Storybook's ESLint plugin

- .changeset/fresh-hounds-pretend.md
- package-lock.json
- package.json
- src/lib/files.ts
[Prettier v3 was released in July 2023](https://prettier.io/blog/2023/07/05/3.0.0). The most notable change for us is the migration to ESM and a fully asynchronous API. Prettier is still compatible with CJS codebases and doesn't break Foundry's support for ESLint (which doesn't support ESM yet).
- Upgrade to Prettier v3
- Migrate to the asynchronous API
> Upgrade to Prettier v3

- .changeset/dull-elephants-roll.md
- README.md
- package-lock.json
- package.json
- src/configs/lint-staged/__snapshots__/config.spec.ts.snap
- src/configs/lint-staged/config.ts
- src/configs/stylelint/config.spec.ts
- src/configs/stylelint/config.ts
- src/configs/stylelint/index.ts
- src/presets/index.ts
- src/stylelint.ts
- src/types/shared.ts
SumUp is slowly replacing Emotion.js with CSS Modules. One benefit of writing vanilla CSS in separate files is that we can use [Stylelint](https://stylelint.io/) to catch errors and enforce a consistent code style.
- Install Stylelint and some plugins
- Create a sensible base config
> Add Stylelint to lint CSS

- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
This rule produces too many false positives.
- Disable [security/detect-object-injection](https://github.com/eslint-community/eslint-plugin-security/blob/main/docs/the-dangers-of-square-bracket-notation.md) rule
> Disable security/detect-object-injection rule

- .changeset/empty-eagles-rule.md
- .changeset/plenty-needles-hunt.md
- CHANGELOG.md
- README.md
- src/types/shared.ts
#923 changes how the ESLint configuration is detected and requires developers to explicitly install ESLint plugins for frameworks.
- Document the new approach in the README
- Add migration instructions to the changelog
> Document the new config detection logic

- .changeset/nervous-dolphins-fix.md
- .changeset/silly-seals-arrive.md
- README.md
- src/cli/debug.ts
- src/cli/defaults.ts
- src/cli/index.ts
- src/cli/init.ts
- src/lib/logger.ts
- src/lib/options.ts
- src/types/shared.ts
Foundry does a lot of magic to detect the appropriate configuration for a project. When it fails, it can be difficult to debug why. The `debug` command is intended to enable developers to inspect the detected options.
- Log detected configuration
- Remove the obsolete `publish` option
> Add more info to debug command

- .changeset/green-wasps-repeat.md
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
End-to-end tests might be nested in a subfolder inside monorepos.
- Changed the file glob to account for nested e2e test folders
> Fix e2e test plugin scope to better support monorepos

- .changeset/red-chefs-vanish.md
- src/cli/init.ts
- src/configs/index.ts
- src/presets/index.ts
In #916, I forgot to add Stylelint to the list of tools, thus breaking the `foundry init` command.
- Add Stylelint to the list of tools
> Fix Stylelint initialization

- package-lock.json
- package.json
Follow-up to #926. Relates to https://github.com/stormwarning/stylelint-config-recess-order/pull/352.
- Upgrade `stylelint-config-recess-order` to v5 to support Stylelint 16
> Upgrade stylelint-config-recess-order to v5

- .changeset/gentle-adults-protect.md
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.spec.ts
- src/configs/eslint/config.ts
- src/lib/options.ts
- src/types/shared.ts
Foundry v7 broadened the glob pattern for integration test files to support monorepos better. This had the unfortunate side-effect that integration test lint rules were wrongly applied to unit test files.
- Reduce the scope of the integration test glob patterns to the `e2e` and `tests` folders at the repo or workspace root
> Reduce the scope of the integration test globs

- .changeset/tough-geckos-turn.md
- src/configs/eslint/config.spec.ts
- src/configs/stylelint/__snapshots__/config.spec.ts.snap
- src/configs/stylelint/config.spec.ts
- src/configs/stylelint/config.ts
- src/lib/options.ts
Circuit UI offers both an ESLint and a Stylelint plugin to ensure the correct usage of its design tokens.
- Automatically configure [Circuit UI's Stylelint plugin](https://circuit.sumup.com/?path=/docs/packages-stylelint-plugin-circuit-ui--docs) when it is installed
> Add support for Circuit UI's Stylelint plugin

- CONTRIBUTING.md
Our contributor license agreement (CLA) bot has been unmaintained and broken for a while, leading to confusion for internal contributors. This project is intended for internal use and hasn't received external contributions recently, so we've decided to remove the CLA bot and only allow contributions from SumUp employees.
- Discourage external contributions
> Discourage external contributions

- .changeset/chatty-squids-happen.md
- .changeset/dirty-crews-suffer.md
- .changeset/fair-timers-joke.md
- .changeset/unlucky-boxes-clap.md
- .github/workflows/ci.yaml
- package-lock.json
- package.json
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
[`eslint-plugin-security` v3](https://github.com/eslint-community/eslint-plugin-security/blob/main/CHANGELOG.md#300-2024-04-10) adds support for ESLint v9 and raises the minimum Node version to ^18.18.0 || ^20.9.0 || >=21.1.0.
I've raised Foundry's minimum Node version to ^18.18 || ^20.9 || >=22 (ie. excluding Node 21, in accordance with our policy of supporting only active LTS versions).
- Upgrade to `eslint-plugin-security` v3
- Raise the minimum Node version to ^18.18 || ^20.9 || >=22 and add Node 22 to the CI test matrix
- Dedupe the dependencies
> Upgrade to eslint-plugin-security v3

- .changeset/famous-lemons-relate.md
- src/configs/eslint/__snapshots__/config.spec.ts.snap
- src/configs/eslint/config.ts
@hilleer reported on Slack that occasionally, Prettier's formatting rules conflict with formatting rules enforced by ESLint. These conflicts were supposed to be resolved by [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier), however, the `airbnb-base` config re-enabled some conflicting rules.
- Switch the order of the `airbnb-base` and `prettier` configs
- Remove custom overrides for conflicting rules
> Fix conflicts between Prettier and ESLint formatting rules

- .changeset/plenty-cows-cross.md
- src/configs/lint-staged/__snapshots__/config.spec.ts.snap
- src/configs/lint-staged/config.ts
When committing changes only to CSS files listed in `.stylelintignore`, Stylelint throws an error.
- Allow empty input to Stylelint on precommit
> Allow empty Stylelint input on precommit

- .eslintrc.js
- package-lock.json
- package.json
- src/configs/eslint/config.ts
- src/configs/eslint/rules/typescript.ts
Addresses [WBPL-411](https://sumupteam.atlassian.net/browse/WBPL-411).
[`eslint-plugin-node`](https://www.npmjs.com/package/eslint-plugin-node) and [`eslint-plugin-import`](https://www.npmjs.com/package/eslint-plugin-import) are no longer maintained and are incompatible with ESLint v9.
Both plugins have replacements ([`eslint-plugin-n`](https://www.npmjs.com/package/eslint-plugin-n) and `[eslint-plugin-import-x`](https://www.npmjs.com/package/eslint-plugin-import-x), however, I plan to install and configure them after the upgrade to ESLint v9, once I've figured out how to use the new flat config.
- Remove `eslint-plugin-node` and `eslint-plugin-import` and disable their associated rules temporarily
> Remove unmaintained ESLint plugins

- .github/workflows/ci.yaml
- .github/workflows/cr.yaml
Foundry can't be tested by locally linking the package due to how it resolves its sub-dependencies.
- Set up https://github.com/stackblitz-labs/pkg.pr.new to publish prereleases for PRs
> Enable continuous releases with pkg.pr.new

- .changeset/polite-paths-vanish.md
- src/configs/stylelint/__snapshots__/config.spec.ts.snap
- src/configs/stylelint/config.spec.ts
- src/configs/stylelint/config.ts
- src/lib/options.spec.ts
- src/lib/options.ts
- src/types/shared.ts
Review and update the supported ESLint and Stylelint plugin version ranges.
- Remove support for old Circuit UI package scope (`@sumup/*`)
- Remove support for ESLint plugins that don't support the new flat config
- Add support for latest plugin versions
> Update supported plugin version ranges

- .changeset/proud-poets-wash.md
- README.md
- package-lock.json
- package.json
- src/cli/defaults.ts
- src/cli/index.ts
- src/cli/init.ts
- src/configs/eslint/index.spec.ts
- src/configs/eslint/index.ts
- src/types/shared.ts
Due to loose types, an incomplete options object is passed to the tools to initialize their config files, causing the ESLint config to miss relevant plugins.
- Tighten up the types
- Pass the right options object to the tool files functions
- Remove the `openSource` CLI flag
> Fix init options
